name = "laouc-agenda-mcp"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
AGENDA_JSON_URL = "https://raw.githubusercontent.com/<github-user>/mcp-agenda-server/master/data/agenda-publica.json"
